name: Run Python Script

# Triggers the workflow on every push to the main branch, or manually
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to click a button in GitHub to run it manually

jobs:
  run-file:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download your repository code onto the runner
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Choose your preferred Python version
      
      
      # Step 3: Run the script
      - name: run ls
        run: ls

      
      # Step 3: Run the script
      - name: Execute Python script
        run: python3 hello.py