name: Hello World Branch Workflow

# Controls when the workflow will run
on:
  push:
    branches: 
      - main       # Triggers when pushing to the main branch
      - feature/*  # Triggers when pushing to any branch starting with feature/
  
  # Allows you to manually trigger this workflow from the Actions tab
  workflow_dispatch: 

jobs:
  say-hello:
    runs-on: ubuntu-latest # The virtual environment to run the code

    steps:
      # Step 1: Checks out your repository code onto the runner
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Executes a standard shell command to print Hello World
      - name: Run Hello World
        run: echo "Hello, World Priya!"
